import eu.phisikus.pivonia.TCPServer;

import java.io.IOException;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static void main(String[] args) throws IOException, InterruptedException {
        TCPServer tcpServer = new TCPServer(8080);
        Thread.sleep(100_000L);

    }
}
